### ISSUE TITLE
Continuous stream of new connections

### ISSUE THREAD

**Issue by jkauffmann-legion** [webrtc-rs/mdns#21] opened 2021-10-21 14:11 UTC
Hi,

We have used `webrtc-rs` in our application to stream a video from a Rust backend to a HTML/Javascript client.

The video stream works fine but in the logs of the Rust server, we see a continuous stream of new connections, like that:

```
2021-10-21 10:07:59,628 INFO [webrtc_mdns::conn] Received new connection from 172.20.48.1:54407
2021-10-21 10:07:59,628 INFO [webrtc_mdns::conn] Received new connection from 172.20.48.1:54407
2021-10-21 10:07:59,628 INFO [webrtc_mdns::conn] Received new connection from 172.20.48.1:54407
2021-10-21 10:07:59,628 INFO [webrtc_mdns::conn] Received new connection from 172.20.208.1:54409
2021-10-21 10:07:59,628 INFO [webrtc_mdns::conn] Received new connection from 172.20.208.1:54409
2021-10-21 10:07:59,628 INFO [webrtc_mdns::conn] Received new connection from 172.20.208.1:54409
2021-10-21 10:07:59,628 INFO [webrtc_mdns::conn] Received new connection from 172.20.48.1:54407
2021-10-21 10:07:59,629 INFO [webrtc_mdns::conn] Received new connection from 192.168.0.63:54411
2021-10-21 10:07:59,629 INFO [webrtc_mdns::conn] Received new connection from 192.168.0.63:54411
2021-10-21 10:07:59,629 INFO [webrtc_mdns::conn] Received new connection from 192.168.0.63:54411
2021-10-21 10:07:59,629 INFO [webrtc_mdns::conn] Received new connection from 172.20.208.1:54409
2021-10-21 10:07:59,630 INFO [webrtc_mdns::conn] Received new connection from 192.168.0.63:54411
```

This never stops and every couple of seconds, we see a batch of "new connections". Before we investigate further, is that expected behavior?

If not, do you have any clue what could cause this?

Thank you.

**Comment by rainliu** [comment] 2021-10-22 02:20
same in pion/mdns

```
~/go/src/mdns/examples/server$ ./server 
mdns INFO: 2021/10/21 19:19:11 Receive new connection 10.0.0.233:5353
mdns WARNING: 2021/10/21 19:19:11 Failed to parse mDNS packet parsing/packing of this type isn't available yet
mdns INFO: 2021/10/21 19:19:11 Receive new connection 10.0.0.202:5353
mdns INFO: 2021/10/21 19:19:12 Receive new connection 10.0.0.110:5353
mdns INFO: 2021/10/21 19:19:12 Receive new connection 10.0.0.110:5353
mdns INFO: 2021/10/21 19:19:12 Receive new connection 10.0.0.127:5353
mdns INFO: 2021/10/21 19:19:12 Receive new connection 10.0.0.202:5353
mdns INFO: 2021/10/21 19:19:12 Receive new connection 10.0.0.110:5353
mdns INFO: 2021/10/21 19:19:13 Receive new connection 10.0.0.202:5353
mdns INFO: 2021/10/21 19:19:13 Receive new connection 10.0.0.202:5353
mdns INFO: 2021/10/21 19:19:14 Receive new connection 10.0.0.127:5353
mdns INFO: 2021/10/21 19:19:23 Receive new connection 10.0.0.202:5353
mdns INFO: 2021/10/21 19:19:23 Receive new connection 10.0.0.127:5353
mdns INFO: 2021/10/21 19:19:24 Receive new connection 10.0.0.127:5353

```

**Comment by rainliu** [comment] 2021-10-22 02:20
close this issue, due to expected behavior of mdns

**Closed by rainliu** 2021-10-22 02:20 UTC
